### ISSUE TITLE
相册页和项目页无法正确显示

### ISSUE THREAD

**Issue by renaultphoto** [th720309/hexo-theme-believe#5]
![1](https://user-images.githubusercontent.com/12331261/34067241-adfe7940-e25a-11e7-8c5b-914c21575b8c.png)

以默认标题的形式展现的文章页，主题内配置如下：

```

# basic
title: 行走的肥肥
subtitle: 沉沉的黑夜往往是白天的前奏
favicon: /favicon.ico

#logo
logo: http://tvax3.sinaimg.cn/crop.0.0.749.749.180/52517133ly8fizu48y04aj20ku0kt0u4.jpg

# duoshuo-comment
duoshuo_shortname: 

highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# nav #
nav:
  - id: 首页
    url: .
    icon: home
  - id: 归档
    url: archives
    icon: archive
  - id: 关于
    url: about
    icon: user
  - id: 项目
    url: project
    icon: folder-open
  - id: 相册
    url: photo
    icon: photo
  - id: 留言
    url: guestbook
    icon: edit
  - id: RSS
    url: atom.xml
    icon: send

# cover
cover_img: /images/back.jpg
cover_avator: http://tvax3.sinaimg.cn/crop.0.0.749.749.180/52517133ly8fizu48y04aj20ku0kt0u4.jpg
cover_info: 欢迎来到我的博客</br>by:renault


photo:
  - title: 夜景
    url: http://wx2.sinaimg.cn/large/52517133ly1fgm9uxbwcej20zk0qoqbg.jpg




# photo(four pictures every line)
#photo:
#  - title: 上海·外滩
 #   url: http://oct3pmpde.bkt.clouddn.com/QQ%E5%9B%BE%E7%89%8720160911111234_Snapseed_meitu_3.jpg


# project #
project:
  - title: demo1
    url: https://github.com/th720309/hexo-theme-believe
    sub: 第一个demo
    language: css
  - title: demo2
    url: https://github.com/th720309/hexo-theme-believe
    sub: 第二个demo
    language: css
  - title: demo3
    url: https://github.com/th720309/hexo-theme-believe
    sub: 第三个demo
    language: css

# baiduanalysis
baiduanalysis: 

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

#### RSS 
rss: /atom.xml 


# social
social:
  github: https://github.com/renaultphoto
  weibo: http://weibo.com/renaultphoto
  twitter: https://twitter.com
  facebook: https://facebook.com

footer: Renault

```
